medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "12345678"
      port: 5432
      dbname: medical_warehouse
      schema: analytics  # dbt will write transformed tables here
